Repository RhodiumGroup/daskhub-rhg-config, pull requests merged in 2021-01, with the labels that each got.

#3 Move config into single, custom helm chart
  README.md
  daskhub-rhg/.helmignore
  daskhub-rhg/Chart.yaml
  daskhub-rhg/templates/NOTES.txt
  daskhub-rhg/values-prod.yaml
  daskhub-rhg/values.yaml
  values-all.yml
  values-prod.yaml
Labels: bug

#6 Fix bad daskgateway pod selector
  daskhub-rhg/values-prod.yaml
Labels: bug

#8 a few more cpu request tweaks
  daskhub-rhg/values.yaml
Labels: enhancement

#9 remove duplicate env var in readme
  README.md
Labels: documentation

#10 add self-heal to readme
  README.md
Labels: documentation
